version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: grokking-interview-postgres
    environment:
      POSTGRES_DB: grokking-interview
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  springboot-app:
    build: .
    ports:
      - "9090:9090"
    environment:
      - APP_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/grokking-interview
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - postgres
    restart: on-failure

volumes:
  postgres-data:
