server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grokking-interview
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    show-sql: true